import type { INotificationsResponse } from "../types/notifications/notification.types";

export const mock_notifications_response: INotificationsResponse = {
	notifications: [
		{
			id: 1,
			recipient_id: 1,
			sender_id: 101,
			sender_username: "dj_shadow",
			preview_image: "https://picsum.photos/seed/lofi1/300/200",
			target_type: "post_like",
			target_id: 1,
			is_read: false,
			created_at: "2025-09-02T14:10:00Z",
		},
		{
			id: 2,
			recipient_id: 1,
			sender_id: 102,
			sender_username: "lofi_girl",
			preview_image: "https://i.pravatar.cc/150?img=32",
			target_type: "post_comment",
			target_id: 2,
			content: "Perfect for studying ✨",
			is_read: false,
			created_at: "2025-09-02T13:42:00Z",
		},
		{
			id: 6,
			recipient_id: 1,
			sender_id: 106,
			sender_username: "beatmakerX",
			preview_image: "https://i.pravatar.cc/150?img=15",
			target_type: "message",
			target_id: 0,
			content: "Check out my new beat 🔥",
			is_read: false,
			created_at: "2025-09-02T12:10:00Z",
		},
		{
			id: 7,
			recipient_id: 1,
			sender_id: 107,
			sender_username: "vinyl_lover",
			preview_image: "https://picsum.photos/seed/vinyl/300/200",
			target_type: "post_like",
			target_id: 2,
			is_read: false,
			created_at: "2025-09-02T11:50:00Z",
		},
		{
			id: 8,
			recipient_id: 1,
			sender_id: 108,
			sender_username: "jane_doe",
			preview_image: "https://i.pravatar.cc/150?img=47",
			target_type: "follow",
			target_id: 0,
			is_read: false,
			created_at: "2025-09-02T10:30:00Z",
		},

		// extra unread
		{
			id: 11,
			recipient_id: 1,
			sender_id: 111,
			sender_username: "citypop",
			preview_image: "https://picsum.photos/seed/citypop/300/200",
			target_type: "post_comment",
			target_id: 3,
			content: "This groove is insane 😍",
			is_read: false,
			created_at: "2025-09-02T10:02:00Z",
		},
		{
			id: 12,
			recipient_id: 1,
			sender_id: 112,
			sender_username: "808_addict",
			preview_image: "https://i.pravatar.cc/150?img=5",
			target_type: "message",
			target_id: 0,
			content: "Got stems for trade?",
			is_read: false,
			created_at: "2025-09-02T09:55:00Z",
		},
		{
			id: 13,
			recipient_id: 1,
			sender_id: 113,
			sender_username: "lofi_cafe",
			preview_image: "https://picsum.photos/seed/lofi-cafe/300/200",
			target_type: "post_like",
			target_id: 4,
			is_read: false,
			created_at: "2025-09-02T09:40:00Z",
		},
		{
			id: 14,
			recipient_id: 1,
			sender_id: 114,
			sender_username: "synthwave",
			preview_image: "https://picsum.photos/seed/synthwave/300/200",
			target_type: "post_comment",
			target_id: 5,
			content: "Retro vibes 🌆",
			is_read: false,
			created_at: "2025-09-02T09:18:00Z",
		},
		{
			id: 15,
			recipient_id: 1,
			sender_id: 115,
			sender_username: "microhouse",
			preview_image: "https://i.pravatar.cc/150?img=12",
			target_type: "follow",
			target_id: 0,
			is_read: false,
			created_at: "2025-09-02T09:02:00Z",
		},
		{
			id: 16,
			recipient_id: 1,
			sender_id: 116,
			sender_username: "dubtech",
			preview_image: "https://picsum.photos/seed/dubtech/300/200",
			target_type: "post_like",
			target_id: 6,
			is_read: false,
			created_at: "2025-09-02T08:44:00Z",
		},
		{
			id: 17,
			recipient_id: 1,
			sender_id: 117,
			sender_username: "ambientair",
			preview_image: "https://i.pravatar.cc/150?img=66",
			target_type: "message",
			target_id: 0,
			content: "Sent you a pad preset ☁️",
			is_read: false,
			created_at: "2025-09-02T08:10:00Z",
		},
		{
			id: 18,
			recipient_id: 1,
			sender_id: 118,
			sender_username: "chillhop",
			preview_image: "https://picsum.photos/seed/chillhop/300/200",
			target_type: "post_comment",
			target_id: 7,
			content: "Clean mix!",
			is_read: false,
			created_at: "2025-09-02T07:58:00Z",
		},
		{
			id: 19,
			recipient_id: 1,
			sender_id: 119,
			sender_username: "rnb_soul",
			preview_image: "https://i.pravatar.cc/150?img=21",
			target_type: "post_like",
			target_id: 8,
			is_read: false,
			created_at: "2025-09-02T07:31:00Z",
		},
		{
			id: 20,
			recipient_id: 1,
			sender_id: 120,
			sender_username: "fieldrecord",
			preview_image: "https://picsum.photos/seed/field/300/200",
			target_type: "follow",
			target_id: 0,
			is_read: false,
			created_at: "2025-09-02T07:10:00Z",
		},

		// --- Old notifications (read) ---
		{
			id: 3,
			recipient_id: 1,
			sender_id: 103,
			sender_username: "rockfan92",
			preview_image: "https://picsum.photos/seed/follow/300/200",
			target_type: "follow",
			target_id: 0,
			is_read: true,
			created_at: "2025-09-01T20:05:00Z",
		},
		{
			id: 4,
			recipient_id: 1,
			sender_id: 104,
			sender_username: "trapqueen",
			preview_image: "https://picsum.photos/seed/msg/300/200",
			target_type: "message",
			target_id: 0,
			content: "Wanna collab this weekend?",
			is_read: true,
			created_at: "2025-08-31T09:15:00Z",
		},
		{
			id: 5,
			recipient_id: 1,
			sender_id: 105,
			sender_username: "jazzman",
			preview_image: "https://picsum.photos/seed/jazz/300/200",
			target_type: "post_comment",
			target_id: 2,
			content: "Love the vibe 🎷",
			is_read: true,
			created_at: "2025-08-30T18:45:00Z",
		},
		{
			id: 9,
			recipient_id: 1,
			sender_id: 109,
			sender_username: "house_master",
			preview_image: "https://picsum.photos/seed/house/300/200",
			target_type: "post_like",
			target_id: 1,
			is_read: true,
			created_at: "2025-08-29T21:10:00Z",
		},
		{
			id: 10,
			recipient_id: 1,
			sender_id: 110,
			sender_username: "electro_queen",
			preview_image: "https://i.pravatar.cc/150?img=56",
			target_type: "follow",
			target_id: 0,
			is_read: true,
			created_at: "2025-08-28T15:25:00Z",
		},

		// extra read
		{
			id: 21,
			recipient_id: 1,
			sender_id: 121,
			sender_username: "drumnbass",
			preview_image: "https://picsum.photos/seed/dnb/300/200",
			target_type: "post_like",
			target_id: 9,
			is_read: true,
			created_at: "2025-08-27T22:12:00Z",
		},
		{
			id: 22,
			recipient_id: 1,
			sender_id: 122,
			sender_username: "neo_soul",
			preview_image: "https://i.pravatar.cc/150?img=38",
			target_type: "post_comment",
			target_id: 10,
			content: "Silky smooth 💜",
			is_read: true,
			created_at: "2025-08-27T18:30:00Z",
		},
		{
			id: 23,
			recipient_id: 1,
			sender_id: 123,
			sender_username: "bpm_120",
			preview_image: "https://picsum.photos/seed/bpm120/300/200",
			target_type: "message",
			target_id: 0,
			content: "Tempo of the last track?",
			is_read: true,
			created_at: "2025-08-26T12:02:00Z",
		},
		{
			id: 24,
			recipient_id: 1,
			sender_id: 124,
			sender_username: "cassette",
			preview_image: "https://picsum.photos/seed/cassette/300/200",
			target_type: "follow",
			target_id: 0,
			is_read: true,
			created_at: "2025-08-25T08:44:00Z",
		},
		{
			id: 25,
			recipient_id: 1,
			sender_id: 125,
			sender_username: "deepsea",
			preview_image: "https://picsum.photos/seed/deepsea/300/200",
			target_type: "post_comment",
			target_id: 11,
			content: "Sub bass is wild 🐋",
			is_read: true,
			created_at: "2025-08-24T21:20:00Z",
		},
		{
			id: 26,
			recipient_id: 1,
			sender_id: 126,
			sender_username: "sunsetmix",
			preview_image: "https://picsum.photos/seed/sunset/300/200",
			target_type: "post_like",
			target_id: 12,
			is_read: true,
			created_at: "2025-08-24T19:10:00Z",
		},
		{
			id: 27,
			recipient_id: 1,
			sender_id: 127,
			sender_username: "vapor",
			preview_image: "https://i.pravatar.cc/150?img=63",
			target_type: "message",
			target_id: 0,
			content: "Loved your last set!",
			is_read: true,
			created_at: "2025-08-23T16:05:00Z",
		},
		{
			id: 28,
			recipient_id: 1,
			sender_id: 128,
			sender_username: "bossa",
			preview_image: "https://picsum.photos/seed/bossa/300/200",
			target_type: "follow",
			target_id: 0,
			is_read: true,
			created_at: "2025-08-22T11:00:00Z",
		},
		{
			id: 29,
			recipient_id: 1,
			sender_id: 129,
			sender_username: "nocturne",
			preview_image: "https://picsum.photos/seed/nocturne/300/200",
			target_type: "post_comment",
			target_id: 13,
			content: "Late night perfection 🌙",
			is_read: true,
			created_at: "2025-08-21T23:42:00Z",
		},
		{
			id: 30,
			recipient_id: 1,
			sender_id: 130,
			sender_username: "breakbeat",
			preview_image: "https://picsum.photos/seed/break/300/200",
			target_type: "post_like",
			target_id: 14,
			is_read: true,
			created_at: "2025-08-20T10:18:00Z",
		},
	],
	total_notifications: 30,
	unread_count: 15,
};
