name: Issue List CI
run-name: "📝 [${{ github.workflow }} #${{ github.run_number }}] ${{ github.head_ref }} by @${{ github.actor }}"

on:
    pull_request:
        types: [opened, reopened, synchronize, closed]
        branches:
            - staging
            - main
            - production
    workflow_dispatch:

jobs:
    issue-list:
        uses: T-ESP-ASSTAGJ/infra/.github/workflows/reusable-issue-list.yml@main
        with:
            repository_name: "client"
            issue_prefix: "TEM"
            jira_url: "https://t-esp-asstagj.atlassian.net"
            jira_mail: "jamly.pro@gmail.com"
        secrets:
            JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
            AUTO_DEPLOY_TOKEN: ${{ secrets.AUTO_DEPLOY_TOKEN }}
            PR_BACK_REMINDER_WEBHOOK_URL: ${{ secrets.PR_BACK_REMINDER_WEBHOOK_URL }}
            PR_FRONT_REMINDER_WEBHOOK_URL: ${{ secrets.PR_FRONT_REMINDER_WEBHOOK_URL }}
            PR_DEVOPS_REMINDER_WEBHOOK_URL: ${{ secrets.PR_DEVOPS_REMINDER_WEBHOOK_URL }}