name: JIRA Integration
run-name: "🔷 [${{ github.workflow }} #${{ github.run_number }}] ${{ github.head_ref }} by @${{ github.actor }}"

on:
    pull_request:
        types: [opened, reopened, synchronize, closed]
    workflow_dispatch:

jobs:
    jira-integration:
        uses: T-ESP-ASSTAGJ/infra/.github/workflows/reusable-jira.yml@main
        with:
            repository_name: "client"
            issue_prefix: "TEM"
            jira_url: "https://t-esp-asstagj.atlassian.net"
            jira_mail: "jamly.pro@gmail.com"
        secrets:
            JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
            AUTO_DEPLOY_TOKEN: ${{ secrets.AUTO_DEPLOY_TOKEN }}