name: Main Branch Notifications

on:
  push:
    branches: [main, staging]

jobs:
  discord-merge-notification:
    uses: T-ESP-ASSTAGJ/infra/.github/workflows/reusable_discord-notification.yml@main
    with:
      repository_name: "web"
      target_branch: ${{ github.ref_name }}
    secrets:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      PR_BACK_REMINDER_WEBHOOK_URL: ${{ secrets.PR_BACK_REMINDER_WEBHOOK_URL }}
      PR_FRONT_REMINDER_WEBHOOK_URL: ${{ secrets.PR_FRONT_REMINDER_WEBHOOK_URL }}
      PR_DEVOPS_REMINDER_WEBHOOK_URL: ${{ secrets.PR_DEVOPS_REMINDER_WEBHOOK_URL }}